package org.icm.model;
// Generated 5 Jun, 2012 5:27:43 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CategoryMaster generated by hbm2java
 */
@Entity
@Table(name="category_master"
    ,catalog="icm"
)
public class CategoryMaster  implements java.io.Serializable {


     private Integer categoryId;
     private String categoryName;
     private String parentCategoryName;
     private Date lastModifiedDate;

    public CategoryMaster() {
    }

    public CategoryMaster(String categoryName, String parentCategoryName, Date lastModifiedDate) {
       this.categoryName = categoryName;
       this.parentCategoryName = parentCategoryName;
       this.lastModifiedDate = lastModifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="categoryId", unique=true, nullable=false)
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    
    @Column(name="categoryName", nullable=false, length=50)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    
    @Column(name="parentCategoryName", nullable=false, length=50)
    public String getParentCategoryName() {
        return this.parentCategoryName;
    }
    
    public void setParentCategoryName(String parentCategoryName) {
        this.parentCategoryName = parentCategoryName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastModifiedDate", nullable=false, length=19)
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }




}


