package org.icm.model;
// Generated 5 Jun, 2012 5:27:43 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemAnalytics generated by hbm2java
 */
@Entity
@Table(name="item_analytics"
    ,catalog="icm"
)
public class ItemAnalytics  implements java.io.Serializable {


     private Integer id;
     private Integer itemId;
     private Integer categoryId;
     private Integer views;
     private Integer downloads;
     private Integer userId;
     private Date lastModifiedDate;

    public ItemAnalytics() {
    }

	
    public ItemAnalytics(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
    public ItemAnalytics(Integer itemId, Integer categoryId, Integer views, Integer downloads, Integer userId, Date lastModifiedDate) {
       this.itemId = itemId;
       this.categoryId = categoryId;
       this.views = views;
       this.downloads = downloads;
       this.userId = userId;
       this.lastModifiedDate = lastModifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="itemId")
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    
    @Column(name="categoryId")
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    
    @Column(name="views")
    public Integer getViews() {
        return this.views;
    }
    
    public void setViews(Integer views) {
        this.views = views;
    }
    
    @Column(name="downloads")
    public Integer getDownloads() {
        return this.downloads;
    }
    
    public void setDownloads(Integer downloads) {
        this.downloads = downloads;
    }
    
    @Column(name="userId")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastModifiedDate", nullable=false, length=19)
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }




}


