package org.icm.model;
// Generated 5 Jun, 2012 5:27:43 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LyricsMaster generated by hbm2java
 */
@Entity
@Table(name="lyrics_master"
    ,catalog="icm"
)
public class LyricsMaster  implements java.io.Serializable {


     private Integer lyricsId;
     private LanguageMaster languageMaster;
     private String title;
     private String lyrics;
     private String albumName;
     private String keywords;
     private String artists;
     private Date lastModifiedDate;

    public LyricsMaster() {
    }

	
    public LyricsMaster(LanguageMaster languageMaster, String title, String lyrics, Date lastModifiedDate) {
        this.languageMaster = languageMaster;
        this.title = title;
        this.lyrics = lyrics;
        this.lastModifiedDate = lastModifiedDate;
    }
    public LyricsMaster(LanguageMaster languageMaster, String title, String lyrics, String albumName, String keywords, String artists, Date lastModifiedDate) {
       this.languageMaster = languageMaster;
       this.title = title;
       this.lyrics = lyrics;
       this.albumName = albumName;
       this.keywords = keywords;
       this.artists = artists;
       this.lastModifiedDate = lastModifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="lyricsId", unique=true, nullable=false)
    public Integer getLyricsId() {
        return this.lyricsId;
    }
    
    public void setLyricsId(Integer lyricsId) {
        this.lyricsId = lyricsId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="languageId", nullable=false)
    public LanguageMaster getLanguageMaster() {
        return this.languageMaster;
    }
    
    public void setLanguageMaster(LanguageMaster languageMaster) {
        this.languageMaster = languageMaster;
    }
    
    @Column(name="title", nullable=false, length=50)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="lyrics", nullable=false, length=5000)
    public String getLyrics() {
        return this.lyrics;
    }
    
    public void setLyrics(String lyrics) {
        this.lyrics = lyrics;
    }
    
    @Column(name="albumName", length=50)
    public String getAlbumName() {
        return this.albumName;
    }
    
    public void setAlbumName(String albumName) {
        this.albumName = albumName;
    }
    
    @Column(name="keywords", length=200)
    public String getKeywords() {
        return this.keywords;
    }
    
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }
    
    @Column(name="artists", length=50)
    public String getArtists() {
        return this.artists;
    }
    
    public void setArtists(String artists) {
        this.artists = artists;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastModifiedDate", nullable=false, length=19)
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }




}


