package org.icm.jaxb.util;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2011.12.12 at 02:23:26 PM IST 
//
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}provider-unique-id"/>
 *         &lt;element ref="{}dle-type"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}caption"/>
 *         &lt;element ref="{}meta" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}inherit-meta-data"/>
 *         &lt;element ref="{}resources" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "download-item")
public class DownloadItem {

	@XmlElement(name = "provider-unique-id", required = true)
	protected String providerUniqueId;
	@XmlElement(name = "dle-type", required = true)
	protected String dleType;
	@XmlElement(required = true)
	protected String name;
	@XmlElement(required = true)
	protected String caption;
	protected List<Meta> meta;
	@XmlElement(required = true)
	@XmlElementWrapper(name = "resources")
	protected List<Resource> resource;

	/**
	 * Gets the value of the providerUniqueId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProviderUniqueId() {
		return providerUniqueId;
	}

	/**
	 * Sets the value of the providerUniqueId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProviderUniqueId(String value) {
		this.providerUniqueId = value;
	}

	/**
	 * Gets the value of the dleType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDleType() {
		return dleType;
	}

	/**
	 * Sets the value of the dleType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDleType(String value) {
		this.dleType = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the caption property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCaption() {
		return caption;
	}

	/**
	 * Sets the value of the caption property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCaption(String value) {
		this.caption = value;
	}

	/**
	 * Gets the value of the meta property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the meta property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMeta().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Meta }
	 * 
	 * 
	 */
	public List<Meta> getMeta() {
		if (meta == null) {
			meta = new ArrayList<Meta>();
		}
		return this.meta;
	}

	/**
	 * Gets the value of the resources property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the resources property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getResources().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Resources }
	 * 
	 * 
	 */
	public List<Resource> getResources() {
		if (resource == null) {
			resource = new ArrayList<Resource>();
		}
		return this.resource;
	}

}
