//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.16 at 06:44:29 PM IST 
//


package org.icm.jaxb.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}header"/>
 *         &lt;element ref="{}leftside"/>
 *         &lt;element ref="{}rightside"/>
 *         &lt;element ref="{}body"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "leftside",
    "rightside",
    "body"
})
@XmlRootElement(name = "layout")
public class Layout {

    @XmlElement(required = true)
    protected Header header;
    @XmlElement(required = true)
    protected Leftside leftside;
    @XmlElement(required = true)
    protected Rightside rightside;
    @XmlElement(required = true)
    protected Body body;
    
 
    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the leftside property.
     * 
     * @return
     *     possible object is
     *     {@link Leftside }
     *     
     */
    public Leftside getLeftside() {
        return leftside;
    }

    /**
     * Sets the value of the leftside property.
     * 
     * @param value
     *     allowed object is
     *     {@link Leftside }
     *     
     */
    public void setLeftside(Leftside value) {
        this.leftside = value;
    }

    /**
     * Gets the value of the rightside property.
     * 
     * @return
     *     possible object is
     *     {@link Rightside }
     *     
     */
    public Rightside getRightside() {
        return rightside;
    }

    /**
     * Sets the value of the rightside property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rightside }
     *     
     */
    public void setRightside(Rightside value) {
        this.rightside = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link Body }
     *     
     */
    public Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link Body }
     *     
     */
    public void setBody(Body value) {
        this.body = value;
    }

}
