//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.16 at 06:44:29 PM IST 
//


package org.icm.jaxb.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ls1"/>
 *         &lt;element ref="{}ls2"/>
 *         &lt;element ref="{}ls3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ls1",
    "ls2",
    "ls3"
})
@XmlRootElement(name = "leftside")
public class Leftside {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ls1;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ls2;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ls3;

    /**
     * Gets the value of the ls1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLs1() {
        return ls1;
    }

    /**
     * Sets the value of the ls1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLs1(String value) {
        this.ls1 = value;
    }

    /**
     * Gets the value of the ls2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLs2() {
        return ls2;
    }

    /**
     * Sets the value of the ls2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLs2(String value) {
        this.ls2 = value;
    }

    /**
     * Gets the value of the ls3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLs3() {
        return ls3;
    }

    /**
     * Sets the value of the ls3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLs3(String value) {
        this.ls3 = value;
    }

}
