//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.16 at 06:44:29 PM IST 
//


package org.icm.jaxb.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}rs1"/>
 *         &lt;element ref="{}rs2"/>
 *         &lt;element ref="{}rs3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rs1",
    "rs2",
    "rs3"
})
@XmlRootElement(name = "rightside")
public class Rightside {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String rs1;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String rs2;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String rs3;

    /**
     * Gets the value of the rs1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRs1() {
        return rs1;
    }

    /**
     * Sets the value of the rs1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRs1(String value) {
        this.rs1 = value;
    }

    /**
     * Gets the value of the rs2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRs2() {
        return rs2;
    }

    /**
     * Sets the value of the rs2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRs2(String value) {
        this.rs2 = value;
    }

    /**
     * Gets the value of the rs3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRs3() {
        return rs3;
    }

    /**
     * Sets the value of the rs3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRs3(String value) {
        this.rs3 = value;
    }

}
